### ISSUE TITLE
Trying to set property "wave" on audiotestsrc

### ISSUE THREAD

**Issue by db-tech** [tinyzimmer/go-gst#53]
Hi,

we're trying to change the wave property of audiotestsrc but we always get the error 
`Invalid type gint for property wave`

which is true, because he want's the `GstAudioTestSrcWave`. 
Is there a way to get this to work ?

```
	propertyType, err := audiotestsrcElement.GetPropertyType("wave")
	if err != nil {
		return nil, err
	}
	err = audiotestsrcElement.Set("wave", 5)
	if err != nil {
		return nil, err
	}
```

**Comment by fzwoch** [comment]
Looks like
https://github.com/tinyzimmer/go-gst/blob/9ce4fbdc33e9ebd07562623f8e0513dc54d868d8/gst/gst_object.go#L57
is a wrapper for
https://gstreamer.freedesktop.org/documentation/gstreamer/gstutils.html#gst_util_set_object_arg
which sounds like what you are looking for.

**Comment by db-tech** [comment]
Yeah thank you, this works! it's just a bit of a shame that is does not return an error.

**Comment by brucekim** [comment]
@db-tech Unlike other `SetXXX` functions in go-gst, `SetArg()` doesn`t have any return value, but it is useful for unsupported type in go-gst to set argument into gst object. This reason makes `SetArg()` hard to design a specific type for return nor error as well.

In order to get a proper return value or error, it would be helpful to give correct type of argument to `SetProperty`.
The property `wave` of audiotestsrc takes enum type "GstAudioTestSrcWave".

wave 
“wave” [GstAudioTestSrcWave](https://gstreamer.freedesktop.org/documentation/audiotestsrc/index.html#GstAudioTestSrcWave) *
Oscillator waveform

Flags : Read / Write

Default value : sine (0)
